name: core-server-prod-ci

on:
  push:
    paths:
      - "core/**"
      - ".github/workflows/core-prod.yml"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      OCIR_HOST: <region>.ocir.io
      OCIR_REPO: <region>.ocir.io/${{ secrets.OCI_TENANCY_NS_PROD }}/core-server

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build commons modules
        run: |
         mvn -q -DskipTests clean install -f commons/pom.xml
         mvn -q -DskipTests clean install -f commons-security/pom.xml
         mvn -q -DskipTests clean install -f commons-mongo/pom.xml
         mvn -q -DskipTests clean install -f commons-mq/pom.xml
         mvn -q -DskipTests clean install -f commons-jooq/pom.xml
         mvn -q -DskipTests clean install -f commons-core/pom.xml


      - name: Build core-server jar
        working-directory: core
        run: mvn -q -DskipTests clean package

      - name: Copy built jar for Dockerfile
        run: |
          mkdir -p target
          cp core/target/*.jar target/

      # - name: Login to OCIR
      #   run: echo "${{ secrets.OCIR_AUTH_TOKEN_PROD }}" | docker login $OCIR_HOST -u "${{ secrets.OCIR_USERNAME_PROD }}" --password-stdin

      - name: Build docker image
        run: |
          docker build -t prod/core-server:${{ github.sha }} -f core/Dockerfile .
          docker tag prod/core-server:${{ github.sha }} test/core-server:latest
          # docker push $OCIR_REPO:${{ github.sha }}
          # docker push $OCIR_REPO:latest
