name: eureka-ci

on:
  push:
    paths:
      - "eureka/**"
      - ".github/workflows/eureka.yml"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      OCIR_HOST: <region>.ocir.io
      OCIR_REPO: <region>.ocir.io/${{ secrets.OCI_TENANCY_NS }}/eureka-server

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build commons dependencies
        run: |
          mvn -q -DskipTests clean install -f commons/pom.xml
          mvn -q -DskipTests clean install -f commons-security/pom.xml
          mvn -q -DskipTests clean install -f commons-mongo/pom.xml
          mvn -q -DskipTests clean install -f commons-mq/pom.xml
          mvn -q -DskipTests clean install -f commons-jooq/pom.xml
          mvn -q -DskipTests clean install -f commons-core/pom.xml

      - name: Build eureka jar
        working-directory: eureka
        run: mvn -q -DskipTests clean package

      - name: Copy JAR for Dockerfile
        run: |
          mkdir -p target
          cp eureka/target/eureka-1.1.0.jar target/

      # - name: Login to OCIR
      #   run: echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login $OCIR_HOST -u "${{ secrets.OCIR_USERNAME }}" --password-stdin

      - name: Build docker image
        run: |
          docker build -t test/eureka-server:${{ github.sha }} -f eureka/Dockerfile .
          docker tag test/eureka-server:${{ github.sha }} test/eureka-server:latest
          # docker push $OCIR_REPO:${{ github.sha }}
          # docker push $OCIR_REPO:latest
