name: files-server-ci

on:
  push:
    paths:
      - "files/**"
      - ".github/workflows/files.yml"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      OCIR_HOST: <region>.ocir.io
      OCIR_REPO: <region>.ocir.io/${{ secrets.OCI_TENANCY_NS }}/files-server

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Build commons (required by files-server)
      - name: Build commons dependencies first
        run: |
          mvn -q -DskipTests clean install -f commons/pom.xml
          mvn -q -DskipTests clean install -f commons-core/pom.xml
          mvn -q -DskipTests clean install -f commons-mongo/pom.xml
          mvn -q -DskipTests clean install -f commons-security/pom.xml
          mvn -q -DskipTests clean install -f commons-mq/pom.xml

      - name: Build files-server jar
        working-directory: files
        run: mvn -q -DskipTests clean package

      - name: Copy built jar for Dockerfile
        run: |
          mkdir -p target
          cp files/target/files-1.1.0.jar target/

      # - name: Login to OCIR
      #   run: echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login $OCIR_HOST -u "${{ secrets.OCIR_USERNAME }}" --password-stdin

      - name: Build docker image
        run: |
          docker build -t $OCIR_REPO:${{ github.sha }} -f files/Dockerfile .
          docker tag $OCIR_REPO:${{ github.sha }} $OCIR_REPO:latest

          # docker push $OCIR_REPO:${{ github.sha }}
          # docker push $OCIR_REPO:latest
