name: gateway-server-ci

on:
  push:
    paths:
      - "gateway/**"
      - ".github/workflows/gateway.yml"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test/gateway-server

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build gateway-server jar
        working-directory: gateway
        run: mvn -q -DskipTests clean package

      - name: Copy built jar for Dockerfile
        run: |
          mkdir -p target
          cp gateway/target/gateway-1.1.0.jar target/

      # - name: Login to OCIR
      #   run: |
      #     echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login $OCIR_HOST -u "${{ secrets.OCIR_USERNAME }}" --password-stdin

      - name: Build docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} -f gateway/Dockerfile .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          # docker push $OCIR_REPO:${{ github.sha }}
          # docker push $OCIR_REPO:latest
