name: multi-ci

on:
  push:
    paths:
      - "multi/**"
      - ".github/workflows/multi-dev.yml"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      OCIR_HOST: <region>.ocir.io
      OCIR_REPO: <region>.ocir.io/${{ secrets.OCI_TENANCY_NS_DEV }}/multi-server

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build commons dependencies
        run: |
          mvn -q -DskipTests clean install -f commons/pom.xml
          mvn -q -DskipTests clean install -f commons-security/pom.xml
          mvn -q -DskipTests clean install -f commons-mongo/pom.xml
          mvn -q -DskipTests clean install -f commons-mq/pom.xml
          mvn -q -DskipTests clean install -f commons-jooq/pom.xml
          mvn -q -DskipTests clean install -f commons-core/pom.xml

      - name: Build multi jar
        working-directory: multi
        run: mvn -q -DskipTests clean package

      - name: Copy JAR for Dockerfile
        run: |
          mkdir -p target
          cp multi/target/multi-2.0.0.jar target/

      # - name: Login to OCIR
      #   run: echo "${{ secrets.OCIR_AUTH_TOKEN_DEV }}" | docker login $OCIR_HOST -u "${{ secrets.OCIR_USERNAME_DEV }}" --password-stdin

      - name: Build docker image
        run: |
          docker build -t test/multi-server-dev:${{ github.sha }} -f multi/Dockerfile .
          docker tag test/multi-server-dev:${{ github.sha }} test/multi-server:latest
          # docker push $OCIR_REPO:${{ github.sha }}
          # docker push $OCIR_REPO:latest
